import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import ModalProvider from "./providers/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BRERacing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <ModalProvider>{children}</ModalProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
